name: Fetch and Decode

on:
  workflow_dispatch: # 允许你手动点击按钮触发运行
  schedule:
    - cron: '0 0 * * *' # 每天国际标准时间 00:00 (北京时间早上 8:00) 自动运行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        pip install -r requirements.txt

    - name: 执行脚本
      run: python main.py
